[project]
name = "foo"
description="Foo library v2"
requires-python = ">=3.8"
authors = [{name = "Danny Farrell", email = "danpf@uw.edu"}]
version = "2.0.0"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
